### ISSUE TITLE
tfx extension publish - Extension package is malformed/corrupted

### ISSUE THREAD

**Issue by tapasudenia** [microsoft/tfs-cli#362]
Hi All,

I am using tfx 0.8.3, I am able to create .VSIX file locally and publish it. I am doing the same thing using the Azure DevOps pipeline yaml referring to Step 6 on this [link](https://docs.microsoft.com/en-us/azure/devops/extend/develop/add-build-task?view=azure-devops)

The pipeline is able to create and publish package with the name foo.VSIX. The download task is also able to download the package with the same name foo.VSIX. However, when  the pipeline runs the publish stage, it tries to run the below command. The `**.gen**` is getting appended from somewhere an hence I think it  is throwing the malformed error. I am not appending anything of this sort in my yaml publish task 

```tfx extension publish --json --no-color --service-url https://marketplace.visualstudio.com/ --auth-type pat --token *** --vsix foo.gen.vsix --debug-log-stream stderr 0 [ '[command]/opt/hostedtoolcache/tfx/0.8.3/x64/bin/tfx extension publish --json --no-color --service-url ```

Also, the foo.VSIX size is 26,460 KB when generated, 

I am not sure the issue is caused because of the .gen getting added or the VSIX size.

Yaml for publish task

```            - task: PublishAzureDevOpsExtension@3
              displayName: 'Publish ADO extension to marketplace'
              inputs:
                connectTo: 'VsTeam'
                connectedServiceName: 'visual-studio-marketplace'
                fileType: 'vsix'
                vsixFile: '*.vsix'
                publisherId: '$(publisherId)'
                extensionId: '$(extensionId)'
                extensionName: '$(extensionName)'
                updateTasksVersion: false
                extensionVisibility: 'private'
                extensionPricing: 'free'
```

**Error:**

2020-11-06T22:59:43.0592466Z [command]/opt/hostedtoolcache/tfx/0.8.3/x64/bin/tfx extension publish --json --no-color --service-url https://marketplace.visualstudio.com/ --auth-type pat --token *** --vsix foo.**gen**.vsix --debug-log-stream stderr 0 [ '[command]/opt/hostedtoolcache/tfx/0.8.3/x64/bin/tfx extension publish --json --no-color --service-url https://marketplace.visualstudio.com/ --auth-type pat --token *** --vsix foo.gen.vsix --debug-log-stream stderr',
2020-11-06T22:59:43.0593723Z   '' ]
2020-11-06T22:59:43.0595050Z  1 [ '[command]/opt/hostedtoolcache/tfx/0.8.3/x64/bin/tfx extension publish --json --no-color --service-url https://marketplace.visualstudio.com/ --auth-type pat --token *** --vsix foo.gen.vsix --debug-log-stream stderr',
2020-11-06T22:59:43.0595780Z   '' ]
2020-11-06T22:59:43.0597093Z (node:5146) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency 0 [ '(node:5146) Warning: Accessing non-existent property \'padLevels\' of module exports inside circular dependency',
2020-11-06T22:59:43.0598178Z   '(Use `node --trace-warnings ...` to show where the warning was created)',
2020-11-06T22:59:43.0598670Z   '' ]
2020-11-06T22:59:43.0599476Z (Use `node --trace-warnings ...` to show where the warning was created) 1 [ '(node:5146) Warning: Accessing non-existent property \'padLevels\' of module exports inside circular dependency',
2020-11-06T22:59:43.0600300Z   '(Use `node --trace-warnings ...` to show where the warning was created)',
2020-11-06T22:59:43.0600685Z   '' ]
2020-11-06T22:59:43.0601266Z  2 [ '(node:5146) Warning: Accessing non-existent property \'padLevels\' of module exports inside circular dependency',
2020-11-06T22:59:43.0601939Z   '(Use `node --trace-warnings ...` to show where the warning was created)',
2020-11-06T22:59:43.0602322Z   '' ]
2020-11-06T22:59:44.0196697Z error: Extension package is malformed/corrupted 0 [ 'error: Extension package is malformed/corrupted', '' ]
2020-11-06T22:59:44.0198221Z  1 [ 'error: Extension package is malformed/corrupted', '' ]
2020-11-06T22:59:44.0275699Z  0 [ '', '' ]
2020-11-06T22:59:44.0278451Z  1 [ '', '' ]
2020-11-06T22:59:44.0369971Z ##[error]tfx failed with error: Error: The process '/opt/hostedtoolcache/tfx/0.8.3/x64/bin/tfx' failed with exit code 255
2020-11-06T22:59:44.3925406Z ##[section]Finishing: Publish ADO extension to marketplace

**Comment by jessehouwing** [comment]
The `.gen` is added by the publish from vsix combined with certain overrides. That is expected, because those overrides aren't supported by `tfx` natively.

26MB is on the too big size and I've seen tfx throw that non-descriptive error in such cases. The error is thrown by tfx. It may be caused by the extract/compress done by this task. 

I'm not 100% what causes it, as tfx doesn't say what it doesn't like about the generated vsix.

**Comment by tapasudenia** [comment]
I could reduce the size to 23MB, pretty less within the size limit of 26MB. I could upload the same VSIX file manually on the market place - https://marketplace.visualstudio.com/

This error is not coming because of the size now.

So this is something else, the error is not clear though

Any other thoughts / suggestions ? I am blocked on this issue now.

**Comment by jessehouwing** [comment]
Pure speculation:

* publish from source with the same settings should work. If needed build the vsix with all overrides in your build stage and turn off overrides in the publish task. 
* try adding a 'Use Node 10.x' task prior to calling the 'use tfx-cli" and packaging/publishing task
* try running the publish stage from either Ubuntu-latest or windows-latest (windows uses 7zip to rezip the package, Ubuntu uses unzip/zip.

You are still getting lots of warnings from node when invoking tfx, my guess is that tfx is broken, try raising the issue there as well, I am external to Microsoft and don't have direct relations with the one maintaining tfx at the moment.

**Comment by tapasudenia** [comment]
Thanks for the suggestions. I am running it from Ubuntu-latest, doesn't work. I also tried validating the package with this command , which returns valid,  but it just doesn't fly through the pipeline. 

Yes, I noticed there are lot warnings when invoking tfx, I am doubting tfx too.

```tfx extension isvalid --publisher MY-PUBLISHER--extension-id MY-EXTENSION-ID --vsix foo.vsix 

Valid```

**Comment by jessehouwing** [comment]
Is valid looks at the last published extension on the marketplace. It doesn't validate the whole package. Unfortunately.

**Comment by tapasudenia** [comment]
Thanks for sharing that. 

I am blocked on this issue for now, Still searching for alternatives

**Comment by jessehouwing** [comment]
Looks like the node warning is caused by using Node 14 or higher.
https://github.com/nodejs/node/issues/32987

Tfx was built against node 4 and hasn't received a lot of love recently. Have you tried putting a 'Use Node 10' task in front of the Publish Extension task?

I test the extension exclusively in node 6 and node 10 as those are the versions currently supported by build tasks (what I normally build). If your extension uses a newer version of node to build, you could try changing the node version before running the Publish Extension task. Either by using the 'use node' task or running the job with `container:'node:10'`.

Maybe I'll find some time to play with this in the upcoming week, but this is a hobby project on my end and I can't promise anything.

**Comment by tapasudenia** [comment]
Thanks for the suggestion, so I tried adding this task before the publish task - [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/tool/node-js?view=azure-devops), but the pipeline failed again with the same error

```            
- task: NodeTool@0
  inputs:
     versionSpec: '10.0'
     checkLatest: false
```

**Comment by tapasudenia** [comment]
So, I tried instead of making use of the manifest.json file instead of using the VSIX file, with the help of the hook `patternManifest` which also gave the same error

```
            - task: PublishAzureDevOpsExtension@3
              displayName: 'Publish Extension'
              inputs:
                connectedServiceName: 'visual-studio-marketplace'
                rootFolder: '$(System.DefaultWorkingDirectory)'
                localizationRoot: '$(System.DefaultWorkingDirectory)'
                patternManifest: 'vss-extension-${{ parameters.env }}.json'
                publisherId: '$(publisherId)'
                extensionId: '$(extensionId)'
                extensionName: '$(extensionName)'
                updateTasksVersionType: patch
                extensionVisibility: private
                extensionPricing: free
```

**Comment by jessehouwing** [comment]
Can I get a private copy of your repo to test against?

**Comment by tapasudenia** [comment]
Hi Jesse,

Alright, so did a `npx depcheck` and I found there were couple of unused dependencies, I did remove all unused dependencies and then by using this task in my pipeline. It worked finally.  I am still wondering, what caused it. But it worked.

```
   displayName: 'Publish ADO extension to marketplace'
              inputs:
                connectTo: 'VsTeam'
                connectedServiceName: 'visual-studio-marketplace'
                fileType: 'vsix'
                vsixFile: '*.vsix'
                publisherId: '$(publisherId)'
                extensionId: '$(extensionId)'
                extensionName: '$(extensionName)'
                updateTasksVersion: false
                extensionVisibility: 'private'
                extensionPricing: 'free'
```
